<HTML>
<HEAD>
<meta charset="UTF-8">
<title>FlowException - corda</title>
<link rel="stylesheet" href="../../../style.css">
</HEAD>
<BODY>
<a href="../../index.html">corda</a>&nbsp;/&nbsp;<a href="../index.html">net.corda.core.flows</a>&nbsp;/&nbsp;<a href="./index.html">FlowException</a><br/>
<br/>
<h1>FlowException</h1>
<code><span class="keyword">open</span> <span class="keyword">class </span><span class="identifier">FlowException</span>&nbsp;<span class="symbol">:</span>&nbsp;<a href="../../net.corda.core/-corda-exception/index.html"><span class="identifier">CordaException</span></a><span class="symbol">, </span><span class="identifier">IdentifiableException</span></code>
<p>Exception which can be thrown by a <a href="../-flow-logic/index.html">FlowLogic</a> at any point in its logic to unexpectedly bring it to a permanent end.
The exception will propagate to all counterparty flows and will be thrown on their end the next time they wait on a
<a href="../-flow-session/receive.html">FlowSession.receive</a> or <a href="../-flow-session/send-and-receive.html">FlowSession.sendAndReceive</a>. Any flow which no longer needs to do a receive, or has already
ended, will not receive the exception (if this is required then have them wait for a confirmation message).</p>
<p>If the <em>rethrown</em> <a href="./index.html">FlowException</a> is uncaught in counterparty flows and propagation triggers then the exception is
downgraded to an <a href="../-unexpected-flow-end-exception/index.html">UnexpectedFlowEndException</a>. This means only immediate counterparty flows will receive information
about what the exception was.</p>
<p><a href="./index.html">FlowException</a> (or a subclass) can be a valid expected response from a flow, particularly ones which act as a service.
It is recommended a <a href="../-flow-logic/index.html">FlowLogic</a> document the <a href="./index.html">FlowException</a> types it can throw.</p>
<h3>Constructors</h3>
<table>
<tbody>
<tr>
<td>
<h4><a href="-init-.html">&lt;init&gt;</a></h4>
</td>
<td>
<code><span class="identifier">FlowException</span><span class="symbol">(</span><span class="identifier" id="net.corda.core.flows.FlowException$<init>(kotlin.String, kotlin.Throwable)/message">message</span><span class="symbol">:</span>&nbsp;<a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-string/index.html"><span class="identifier">String</span></a><span class="symbol">?</span><span class="symbol">, </span><span class="identifier" id="net.corda.core.flows.FlowException$<init>(kotlin.String, kotlin.Throwable)/cause">cause</span><span class="symbol">:</span>&nbsp;<a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-throwable/index.html"><span class="identifier">Throwable</span></a><span class="symbol">?</span><span class="symbol">)</span></code><br/>
<code><span class="identifier">FlowException</span><span class="symbol">(</span><span class="identifier" id="net.corda.core.flows.FlowException$<init>(kotlin.String)/message">message</span><span class="symbol">:</span>&nbsp;<a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-string/index.html"><span class="identifier">String</span></a><span class="symbol">?</span><span class="symbol">)</span></code><br/>
<code><span class="identifier">FlowException</span><span class="symbol">(</span><span class="identifier" id="net.corda.core.flows.FlowException$<init>(kotlin.Throwable)/cause">cause</span><span class="symbol">:</span>&nbsp;<a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-throwable/index.html"><span class="identifier">Throwable</span></a><span class="symbol">?</span><span class="symbol">)</span></code><br/>
<code><span class="identifier">FlowException</span><span class="symbol">(</span><span class="symbol">)</span></code>
<p>Exception which can be thrown by a <a href="../-flow-logic/index.html">FlowLogic</a> at any point in its logic to unexpectedly bring it to a permanent end.
The exception will propagate to all counterparty flows and will be thrown on their end the next time they wait on a
<a href="../-flow-session/receive.html">FlowSession.receive</a> or <a href="../-flow-session/send-and-receive.html">FlowSession.sendAndReceive</a>. Any flow which no longer needs to do a receive, or has already
ended, will not receive the exception (if this is required then have them wait for a confirmation message).</p>
<code><span class="identifier">FlowException</span><span class="symbol">(</span><span class="identifier" id="net.corda.core.flows.FlowException$<init>(kotlin.String, kotlin.Throwable, kotlin.Long)/message">message</span><span class="symbol">:</span>&nbsp;<a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-string/index.html"><span class="identifier">String</span></a><span class="symbol">?</span><span class="symbol">, </span><span class="identifier" id="net.corda.core.flows.FlowException$<init>(kotlin.String, kotlin.Throwable, kotlin.Long)/cause">cause</span><span class="symbol">:</span>&nbsp;<a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-throwable/index.html"><span class="identifier">Throwable</span></a><span class="symbol">?</span><span class="symbol">, </span><span class="identifier" id="net.corda.core.flows.FlowException$<init>(kotlin.String, kotlin.Throwable, kotlin.Long)/originalErrorId">originalErrorId</span><span class="symbol">:</span>&nbsp;<a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-long/index.html"><span class="identifier">Long</span></a><span class="symbol">?</span>&nbsp;<span class="symbol">=</span>&nbsp;null<span class="symbol">)</span></code></td>
</tr>
</tbody>
</table>
<h3>Properties</h3>
<table>
<tbody>
<tr>
<td>
<h4><a href="original-error-id.html">originalErrorId</a></h4>
</td>
<td>
<p>the ID backing <a href="get-error-id.html">getErrorId</a>. If null it will be set dynamically by the flow framework when
    the exception is handled. This ID is propagated to counterparty flows, even when the <a href="./index.html">FlowException</a> is
    downgraded to an <a href="../-unexpected-flow-end-exception/index.html">UnexpectedFlowEndException</a>. This is so the error conditions may be correlated later on.</p>
<code><span class="keyword">var </span><span class="identifier">originalErrorId</span><span class="symbol">: </span><a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-long/index.html"><span class="identifier">Long</span></a><span class="symbol">?</span></code></td>
</tr>
</tbody>
</table>
<h3>Functions</h3>
<table>
<tbody>
<tr>
<td>
<h4><a href="get-error-id.html">getErrorId</a></h4>
</td>
<td>
<code><span class="keyword">open</span> <span class="keyword">fun </span><span class="identifier">getErrorId</span><span class="symbol">(</span><span class="symbol">)</span><span class="symbol">: </span><a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-long/index.html"><span class="identifier">Long</span></a><span class="symbol">?</span></code></td>
</tr>
</tbody>
</table>
<h3>Inheritors</h3>
<table>
<tbody>
<tr>
<td>
<h4><a href="../../net.corda.core.contracts/-attachment-resolution-exception/index.html">AttachmentResolutionException</a></h4>
</td>
<td>
<p>The node asked a remote peer for the attachment identified by <a href="../../net.corda.core.contracts/-attachment-resolution-exception/hash.html">hash</a> because it is a dependency of a transaction
being resolved, but the remote peer would not provide it.</p>
<code><span class="keyword">class </span><span class="identifier">AttachmentResolutionException</span>&nbsp;<span class="symbol">:</span>&nbsp;<a href="./index.html"><span class="identifier">FlowException</span></a></code></td>
</tr>
<tr>
<td>
<h4><a href="../../net.corda.testing.dsl/-attachment-resolution-exception/index.html">AttachmentResolutionException</a></h4>
</td>
<td>
<code><span class="keyword">class </span><span class="identifier">AttachmentResolutionException</span>&nbsp;<span class="symbol">:</span>&nbsp;<a href="./index.html"><span class="identifier">FlowException</span></a></code></td>
</tr>
<tr>
<td>
<h4><a href="../../net.corda.core.contracts/-broken-attachment-exception/index.html">BrokenAttachmentException</a></h4>
</td>
<td>
<p>A non-specific exception for the attachment identified by <a href="../../net.corda.core.contracts/-broken-attachment-exception/attachment-id.html">attachmentId</a>. The context
for this error is provided via the <a href="#">message</a> and <a href="#">cause</a>.</p>
<code><span class="keyword">class </span><span class="identifier">BrokenAttachmentException</span>&nbsp;<span class="symbol">:</span>&nbsp;<a href="./index.html"><span class="identifier">FlowException</span></a></code></td>
</tr>
<tr>
<td>
<h4><a href="../../net.corda.finance.flows/-cash-exception/index.html">CashException</a></h4>
</td>
<td>
<code><span class="keyword">class </span><span class="identifier">CashException</span>&nbsp;<span class="symbol">:</span>&nbsp;<a href="./index.html"><span class="identifier">FlowException</span></a></code></td>
</tr>
<tr>
<td>
<h4><a href="../../net.corda.testing.dsl/-double-spent-inputs/index.html">DoubleSpentInputs</a></h4>
</td>
<td>
<code><span class="keyword">class </span><span class="identifier">DoubleSpentInputs</span>&nbsp;<span class="symbol">:</span>&nbsp;<a href="./index.html"><span class="identifier">FlowException</span></a></code></td>
</tr>
<tr>
<td>
<h4><a href="../../net.corda.testing.dsl/-duplicate-output-label/index.html">DuplicateOutputLabel</a></h4>
</td>
<td>
<code><span class="keyword">class </span><span class="identifier">DuplicateOutputLabel</span>&nbsp;<span class="symbol">:</span>&nbsp;<a href="./index.html"><span class="identifier">FlowException</span></a></code></td>
</tr>
<tr>
<td>
<h4><a href="../-flow-recovery-exception/index.html">FlowRecoveryException</a></h4>
</td>
<td>
<code><span class="keyword">class </span><span class="identifier">FlowRecoveryException</span>&nbsp;<span class="symbol">:</span>&nbsp;<a href="./index.html"><span class="identifier">FlowException</span></a></code></td>
</tr>
<tr>
<td>
<h4><a href="../../net.corda.core.contracts/-insufficient-balance-exception/index.html">InsufficientBalanceException</a></h4>
</td>
<td>
<p>Thrown if a request is made to spend an amount of a <a href="../../net.corda.core.contracts/-fungible-asset/index.html">FungibleAsset</a> but there aren't enough tokens in the vault.</p>
<code><span class="keyword">class </span><span class="identifier">InsufficientBalanceException</span>&nbsp;<span class="symbol">:</span>&nbsp;<a href="./index.html"><span class="identifier">FlowException</span></a></code></td>
</tr>
<tr>
<td>
<h4><a href="../-ledger-recovery-exception/index.html">LedgerRecoveryException</a></h4>
</td>
<td>
<code><span class="keyword">class </span><span class="identifier">LedgerRecoveryException</span>&nbsp;<span class="symbol">:</span>&nbsp;<a href="./index.html"><span class="identifier">FlowException</span></a></code></td>
</tr>
<tr>
<td>
<h4><a href="../../net.corda.core.transactions/-missing-contract-attachments/index.html">MissingContractAttachments</a></h4>
</td>
<td>
<p>A contract attachment was missing when trying to automatically attach all known contract attachments</p>
<code><span class="keyword">class </span><span class="identifier">MissingContractAttachments</span>&nbsp;<span class="symbol">:</span>&nbsp;<a href="./index.html"><span class="identifier">FlowException</span></a></code></td>
</tr>
<tr>
<td>
<h4><a href="../-notary-exception/index.html">NotaryException</a></h4>
</td>
<td>
<p>Exception thrown by the notary service if any issues are encountered while trying to commit a transaction. The
underlying <a href="../-notary-exception/error.html">error</a> specifies the cause of failure.</p>
<code><span class="keyword">class </span><span class="identifier">NotaryException</span>&nbsp;<span class="symbol">:</span>&nbsp;<a href="./index.html"><span class="identifier">FlowException</span></a></code></td>
</tr>
<tr>
<td>
<h4><a href="../-state-replacement-exception/index.html">StateReplacementException</a></h4>
</td>
<td>
<code><span class="keyword">open</span> <span class="keyword">class </span><span class="identifier">StateReplacementException</span>&nbsp;<span class="symbol">:</span>&nbsp;<a href="./index.html"><span class="identifier">FlowException</span></a></code></td>
</tr>
<tr>
<td>
<h4><a href="../../net.corda.core.node.services/-states-not-available-exception/index.html">StatesNotAvailableException</a></h4>
</td>
<td>
<code><span class="keyword">class </span><span class="identifier">StatesNotAvailableException</span>&nbsp;<span class="symbol">:</span>&nbsp;<a href="./index.html"><span class="identifier">FlowException</span></a></code></td>
</tr>
<tr>
<td>
<h4><a href="../../net.corda.core.contracts/-transaction-resolution-exception/index.html">TransactionResolutionException</a></h4>
</td>
<td>
<p>The node asked a remote peer for the transaction identified by <a href="../../net.corda.core.contracts/-transaction-resolution-exception/hash.html">hash</a> because it is a dependency of a transaction
being resolved, but the remote peer would not provide it.</p>
<code><span class="keyword">open</span> <span class="keyword">class </span><span class="identifier">TransactionResolutionException</span>&nbsp;<span class="symbol">:</span>&nbsp;<a href="./index.html"><span class="identifier">FlowException</span></a></code></td>
</tr>
<tr>
<td>
<h4><a href="../../net.corda.core.contracts/-transaction-verification-exception/index.html">TransactionVerificationException</a></h4>
</td>
<td>
<p>Indicates that some aspect of the transaction named by <a href="../../net.corda.core.contracts/-transaction-verification-exception/tx-id.html">txId</a> violates the platform rules. The exact type of failure
is expressed using a subclass. TransactionVerificationException is a <a href="./index.html">FlowException</a> and thus when thrown inside
a flow, the details of the failure will be serialised, propagated to the peer and rethrown.</p>
<code><span class="keyword">abstract</span> <span class="keyword">class </span><span class="identifier">TransactionVerificationException</span>&nbsp;<span class="symbol">:</span>&nbsp;<a href="./index.html"><span class="identifier">FlowException</span></a></code></td>
</tr>
<tr>
<td>
<h4><a href="../../net.corda.finance.workflows.utils/-unknown-calendar/index.html">UnknownCalendar</a></h4>
</td>
<td>
<code><span class="keyword">class </span><span class="identifier">UnknownCalendar</span>&nbsp;<span class="symbol">:</span>&nbsp;<a href="./index.html"><span class="identifier">FlowException</span></a></code></td>
</tr>
<tr>
<td>
<h4><a href="../../net.corda.core.node.services/-vault-query-exception/index.html">VaultQueryException</a></h4>
</td>
<td>
<code><span class="keyword">class </span><span class="identifier">VaultQueryException</span>&nbsp;<span class="symbol">:</span>&nbsp;<a href="./index.html"><span class="identifier">FlowException</span></a></code></td>
</tr>
</tbody>
</table>
</BODY>
</HTML>
