<HTML>
<HEAD>
<meta charset="UTF-8">
<title>TransactionVerificationException.<init> - ledger</title>
<link rel="stylesheet" href="../../../style.css">
</HEAD>
<BODY>
<a href="../../index.html">ledger</a>&nbsp;/&nbsp;<a href="../index.html">net.corda.v5.ledger.contracts</a>&nbsp;/&nbsp;<a href="index.html">TransactionVerificationException</a>&nbsp;/&nbsp;<a href="./-init-.html">&lt;init&gt;</a><br/>
<br/>
<h1>&lt;init&gt;</h1>
<a name="net.corda.v5.ledger.contracts.TransactionVerificationException$&lt;init&gt;(net.corda.v5.crypto.SecureHash, kotlin.String, kotlin.Throwable)"></a>
<code><span class="identifier">TransactionVerificationException</span><span class="symbol">(</span><span class="identifier" id="net.corda.v5.ledger.contracts.TransactionVerificationException$<init>(net.corda.v5.crypto.SecureHash, kotlin.String, kotlin.Throwable)/txId">txId</span><span class="symbol">:</span>&nbsp;<span class="identifier">SecureHash</span><span class="symbol">, </span><span class="identifier" id="net.corda.v5.ledger.contracts.TransactionVerificationException$<init>(net.corda.v5.crypto.SecureHash, kotlin.String, kotlin.Throwable)/message">message</span><span class="symbol">:</span>&nbsp;<a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-string/index.html"><span class="identifier">String</span></a><span class="symbol">, </span><span class="identifier" id="net.corda.v5.ledger.contracts.TransactionVerificationException$<init>(net.corda.v5.crypto.SecureHash, kotlin.String, kotlin.Throwable)/cause">cause</span><span class="symbol">:</span>&nbsp;<a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-throwable/index.html"><span class="identifier">Throwable</span></a><span class="symbol">?</span><span class="symbol">)</span></code>
<p>Indicates that some aspect of the transaction named by <a href="tx-id.html">txId</a> violates the platform rules. The exact type of failure
is expressed using a subclass. TransactionVerificationException is a <a href="#">FlowException</a> and thus when thrown inside
a flow, the details of the failure will be serialised, propagated to the peer and rethrown.</p>
</BODY>
</HTML>
